name: Auto Commit and Push

on:
  schedule:
    - cron: '0 10,13,19 * * *'  # Run at 10AM, 1PM, and 7PM
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code using SSH
      uses: actions/checkout@v3
      with:
        repository: anilrajrimal1/auto-commit-and-chill
        ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run auto commit script
      run: python3 scripts/auto_commit.py
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
